export const toolSchema=[{type:'function',function:{name:'query_building',description:'Query the currently loaded IFC and current room sensor snapshot. Use overview first for valid floors and categories. Counts are exact over all matches, not the paginated sample. Properties/material search searches exported IFC properties only.',parameters:{type:'object',properties:{operation:{type:'string',enum:['overview','elements','sensors']},floor:{type:'string',description:'Exact floor ID or full name from overview; omit for all floors'},type:{type:'string',description:'Exact IFC entity category, e.g. IfcDoor, IfcWindow, IfcSpace'},search:{type:'string',description:'Case-insensitive substring in name, long name, Global ID, Express ID or exported properties'},id:{type:'string',description:'Exact Global ID or Express ID'},offset:{type:'integer',minimum:0},limit:{type:'integer',minimum:1,maximum:40},includeProperties:{type:'boolean'}},required:['operation'],additionalProperties:false}}}];
export function queryBuilding(data,a){
 const all=data.elements;let items=all, floor=null;
 if(a.floor){const matches=data.floors.filter(f=>String(f.id)===a.floor||f.name.toLowerCase()===a.floor.toLowerCase());if(matches.length!==1)return {error:'Unknown or ambiguous floor; use overview and exact floor ID',floors:data.floors};floor=matches[0];items=items.filter(e=>e.floor===floor.id);}
 if(a.type)items=items.filter(e=>e.type.toLowerCase()===a.type.toLowerCase());
 if(a.id)items=items.filter(e=>String(e.id)===a.id||e.guid===a.id);
 if(a.search){const q=a.search.toLowerCase();items=items.filter(e=>JSON.stringify([e.id,e.guid,e.name,e.longName,e.properties]).toLowerCase().includes(q));}
 const counts=list=>list.reduce((o,e)=>(o[e.type]=(o[e.type]||0)+1,o),{});
 if(a.operation==='overview')return {name:data.name,floors:data.floors,countsByType:counts(all),countsByFloor:data.floors.map(f=>({id:f.id,name:f.name,counts:counts(all.filter(e=>e.floor===f.id))})),unassigned:counts(all.filter(e=>!data.floors.some(f=>f.id===e.floor))),sensorNote:'Synthetic unless source says external. IFC properties retain exported units; geometry is metres. Enhanced finishes are inferred, not verified materials.'};
 const offset=Math.max(0,Math.floor(a.offset||0)),limit=Math.max(1,Math.min(40,Math.floor(a.limit||20)));
 if(a.operation==='sensors'){const ids=new Set(items.filter(e=>e.type==='IfcSpace').map(e=>e.guid));const readings=data.readings.filter(r=>ids.has(r.spaceId)).map(r=>({...r,room:all.find(e=>e.guid===r.spaceId)?.name,ageSeconds:Math.max(0,(data.timestamp-r.timestamp)/1000),stale:r.source==='external'&&data.timestamp-r.timestamp>30000}));return {capturedAt:new Date(data.timestamp).toISOString(),units:{temperature:'°C',co2:'ppm',lux:'lux',occupancy:'people'},total:readings.length,offset,readings:readings.slice(offset,offset+limit),nextOffset:offset+limit<readings.length?offset+limit:null};}
 if(a.operation!=='elements')return {error:'Unsupported operation'};
 return {total:items.length,countsByType:counts(items),offset,nextOffset:offset+limit<items.length?offset+limit:null,elements:items.slice(offset,offset+limit).map(e=>({id:e.id,guid:e.guid,name:e.name,longName:e.longName,type:e.type,floor:e.floor,properties:a.includeProperties?e.properties:undefined}))};
}
