import * as THREE from 'three';
import {createSensors,metrics,heatValue} from './sensors.mjs';
const $=id=>document.getElementById(id);
export function installSpaceTools(ctx){
 const {data,root,geom,clipping,invalidate}=ctx,rooms=new Map(),picks=[],materials=[];let selected=null,metric='none',population=120,paused=false;
 for(const el of data.spaces){const g=new THREE.Group();root.add(g);const mat=new THREE.MeshStandardMaterial({color:0x56a9c3,transparent:true,opacity:.48,side:THREE.DoubleSide,depthWrite:false,roughness:1,polygonOffset:true,polygonOffsetFactor:-2,polygonOffsetUnits:-2});materials.push(mat);let area=0;const box=new THREE.Box3();for(const p of el.parts){const source=geom.get(p.geometry).clone();source.applyMatrix4(new THREE.Matrix4().fromArray(p.matrix));source.computeBoundingBox();box.union(source.boundingBox);const pos=source.attributes.position,ix=source.index,verts=[],min=source.boundingBox.min.y,max=source.boundingBox.max.y;for(let i=0;i<ix.count;i+=3){const ids=[ix.getX(i),ix.getX(i+1),ix.getX(i+2)],ys=ids.map(j=>pos.getY(j));if(Math.max(...ys)-Math.min(...ys)<.015&&ys[0]>(min+max)/2){for(const j of ids)verts.push(pos.getX(j),min+.065,pos.getZ(j));const a=new THREE.Vector3().fromBufferAttribute(pos,ids[0]),b=new THREE.Vector3().fromBufferAttribute(pos,ids[1]),c=new THREE.Vector3().fromBufferAttribute(pos,ids[2]);area+=new THREE.Triangle(a,b,c).getArea();}}
 if(!verts.length){const non=source.toNonIndexed(),p2=non.attributes.position;for(let i=0;i<p2.count;i++)verts.push(p2.getX(i),min+.065,p2.getZ(i));non.dispose();}
 const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));geometry.computeVertexNormals();const mesh=new THREE.Mesh(geometry,mat);mesh.userData.space=el.guid;mesh.renderOrder=2;g.add(mesh);picks.push(mesh);source.dispose();}
 const worldBox=box.clone().translate(root.position),capacity=Math.max(2,Math.round(area/6));rooms.set(el.guid,{el,g,mat,box:worldBox,area,capacity});g.visible=false;
 }
 const sensorSpaces=[...rooms].map(([id,r])=>({id,name:r.el.longName||r.el.name,capacity:r.capacity})),sensors=createSensors(sensorSpaces);sensors.step(population);
 const colors=['#497abd','#3cbca8','#e8ce68','#d76559'].map(c=>new THREE.Color(c));function color(t){const a=THREE.MathUtils.clamp(t,0,1)*3,i=Math.min(2,Math.floor(a));return colors[i].clone().lerp(colors[i+1],a-i);}
 function isStale(r){return r.source==='external'&&Date.now()-r.timestamp>30000;}
 function showTab(id){for(const [tab,panel]of [['model','building'],['space','spaces'],['settings','appearance']]){$(tab+'-tab').classList.toggle('active',tab===id);$(panel+'-panel').hidden=tab!==id;}list();}
 for(const id of ['model','space','settings'])$(id+'-tab').onclick=()=>showTab(id);
 for(const f of [...data.floors,...(data.spaces.some(s=>!s.floor)?[{id:0,name:'Unassigned'}]:[])].filter(f=>data.spaces.some(s=>s.floor===f.id))){const op=document.createElement('option');op.value=f.id;op.textContent=f.name;$('space-floor').append(op);}
 function list(){const floor=Number($('space-floor').value),q=$('space-search').value.toLowerCase();$('space-list').replaceChildren();const visible=[...rooms].filter(([id,r])=>r.el.floor===floor&&(r.el.name+' '+r.el.longName).toLowerCase().includes(q)).sort((a,b)=>a[1].el.name.localeCompare(b[1].el.name,undefined,{numeric:true}));$('space-count').textContent=visible.length+' spaces';for(const [id,r]of visible){const b=document.createElement('button'),strong=document.createElement('strong'),small=document.createElement('small');strong.textContent=r.el.name;small.textContent=r.el.longName||'Space';b.append(strong,small);b.classList.toggle('active',selected===id);b.onclick=()=>open(id);$('space-list').append(b);}}
 $('space-floor').onchange=list;$('space-search').oninput=list;
 function paint(){const f=ctx.getFloor();for(const [id,r]of rooms){r.g.visible=(metric!=='none'||id===selected)&&(f==='all'||r.el.floor===f);r.mat.clippingPlanes=$('section').checked?[clipping]:[];r.mat.needsUpdate=true;const read=sensors.readings.get(id);if(metric==='none')r.mat.color.set(id===selected?0x1598b9:0x73b5cc);else{const m=metrics[metric];r.mat.color.copy(isStale(read)?new THREE.Color(0x9da8b4):color((heatValue(metric,read,r.capacity)-m.min)/(m.max-m.min)));}r.mat.opacity=id===selected?.82:.62;}invalidate();}
 function clear(){selected=null;$('sensor-inspector').hidden=true;paint();}
 function open(id){const r=rooms.get(id);if(!r)return;ctx.openRoom(r);selected=id;$('space-floor').value=r.el.floor;showTab('space');$('selection-title').textContent=r.el.name+' · '+(r.el.longName||'Space');$('overview').hidden=true;$('element-actions').hidden=true;$('sensor-inspector').hidden=false;$('properties').replaceChildren();ctx.addProperty('Floor',data.floors.find(f=>f.id===r.el.floor)?.name);ctx.addProperty('IFC space Global ID',r.el.guid);ctx.addProperty('Express ID',r.el.id);ctx.addProperty('Estimated capacity',r.capacity+' people · simulation only');for(const [k,v]of r.el.properties)ctx.addProperty(k,v);list();paint();inspect();}
 function inspect(){if(!selected)return;const r=rooms.get(selected),v=sensors.readings.get(selected);$('sensor-source').textContent=isStale(v)?'EXTERNAL · STALE':v.source==='external'?'EXTERNAL INPUT':paused?'SIMULATION PAUSED':'SIMULATED';$('sensor-age').textContent=v.source==='external'?Math.max(0,Math.floor((Date.now()-v.timestamp)/1000))+'s old':'Every 3 seconds';$('sensor-cards').innerHTML=Object.entries(metrics).map(([k,m])=>`<div class="sensor-card"><span>${m.label}</span><strong>${Number(v[k]).toFixed(k==='temperature'?1:0)}<em>${k==='occupancy'?'people':m.unit}</em></strong><small>${k==='occupancy'?'Capacity ≈ '+r.capacity:v.source==='external'?'Supplied reading':'Simulated'}</small></div>`).join('');$('reset-reading').disabled=v.source!=='external';const key=$('trend').value,h=sensors.history.get(selected),a=h.map(x=>x[key]);if(!a.length)a.push(v[key]);const min=Math.min(...a)-.5,max=Math.max(...a)+.5,points=a.map((x,i)=>`${5+i*270/Math.max(1,a.length-1)},${82-(x-min)/(max-min)*70}`);$('sensor-chart').innerHTML=`<path d="M0 20H280M0 50H280M0 80H280" stroke="#e4edf2"/><polyline points="${points.join(' ')}" stroke="#198bae" stroke-width="2" fill="none"/><circle cx="${points.at(-1).split(',')[0]}" cy="${points.at(-1).split(',')[1]}" r="3" fill="#198bae"/>`;$('sensor-chart').setAttribute('aria-label',metrics[key].label+' history. Current '+v[key]+' '+metrics[key].unit);}
 function tick(){sensors.step(population);inspect();paint();}
 const demo=[...rooms].find(([id,r])=>r.el.floor===38&&!/toilet|stair|corridor|shaft|elev/i.test(r.el.longName))?.[0]||rooms.keys().next().value;
 $('demo-room').disabled=!rooms.size;$('heatmap').disabled=!rooms.size;if(!rooms.size){$('demo-room').textContent='No room geometry in this IFC';$('space-count').textContent='No usable IFC spaces';}$('demo-room').onclick=()=>open(demo);$('heatmap').onchange=()=>{metric=$('heatmap').value;$('heat-legend').hidden=metric==='none';if(metric!=='none'){const m=metrics[metric];$('heat-title').textContent=m.label;$('heat-min').textContent=m.min+' '+m.unit;$('heat-max').textContent=m.max+' '+m.unit;if(!selected)open(demo);}paint();};
 $('population').oninput=()=>{population=Number($('population').value);$('population-value').textContent=population;tick();};$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'Resume simulation':'Pause simulation';inspect();};$('trend').onchange=inspect;
 function ingest(payload){const r=sensors.ingest(payload),h=sensors.history.get(r.spaceId);h.push({...r,recordedAt:Date.now()});if(h.length>60)h.shift();inspect();paint();return {...r};}
 $('send-reading').onclick=()=>{$('payload').value=JSON.stringify({spaceId:selected,temperature:22.8,co2:740,lux:460,occupancy:8},null,2);$('sensor-result').textContent='';$('sensor-dialog').showModal();};$('ingest').onclick=()=>{try{const r=ingest(JSON.parse($('payload').value));$('sensor-result').textContent='Accepted for room '+rooms.get(r.spaceId).el.name+'.';}catch(e){$('sensor-result').textContent=e.message;}};$('reset-reading').onclick=()=>{sensors.reset(selected);tick();};
 window.ifcTwin={spaces:sensorSpaces,selectSpace:open,getReadings:()=>[...sensors.readings.values()].map(x=>({...x})),ingestSensor:ingest,resetSpace:id=>{if(!rooms.has(id))throw Error('Unknown spaceId');sensors.reset(id);tick();}};window.addEventListener('ifc:sensor',e=>{try{ingest(e.detail);}catch(error){$('notice').hidden=false;$('notice').textContent=error.message;setTimeout(()=>$('notice').hidden=true,4000);}});
 
 if(document.modelContext?.registerTool){const lifecycle=new AbortController();const tools=[{name:'list_ifc_spaces',description:'Read the IFC room list and current sensor readings.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({spaces:sensorSpaces,readings:window.ifcTwin.getReadings()})},{name:'select_ifc_space',description:'Open an IFC room cutaway and its sensor inspector.',inputSchema:{type:'object',properties:{spaceId:{type:'string'}},required:['spaceId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>{if(!input||typeof input.spaceId!=='string'||!rooms.has(input.spaceId))throw Error('Unknown spaceId');open(input.spaceId);return {selectedSpaceId:selected};}}];for(const tool of tools){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(console.warn);}catch(error){console.warn(error);}}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
 let last=performance.now(),fresh=last;list();return {picks,rooms,materials,open,clear,paint,step(now){if(now-last>3000){last=now;if(!paused)tick();}if(now-fresh>1000){fresh=now;inspect();if(metric!=='none')paint();}}};
}
