export const metrics={temperature:{label:'Temperature',unit:'°C',min:18,max:28},co2:{label:'CO₂',unit:'ppm',min:400,max:1600},lux:{label:'Brightness',unit:'lx',min:0,max:800},occupancy:{label:'Occupancy',unit:'%',min:0,max:100}};
export function validateReading(payload,spaces,now=Date.now()){
 if(!payload||typeof payload!=='object')throw Error('Provide a JSON object.');const space=spaces.find(s=>s.id===payload.spaceId);if(!space)throw Error('Unknown spaceId.');
 const limits={temperature:[-20,60],co2:[200,10000],lux:[0,20000],occupancy:[0,1000]},out={spaceId:space.id};
 for(const [key,[min,max]]of Object.entries(limits)){const v=payload[key];if(typeof v!=='number'||!Number.isFinite(v)||v<min||v>max||(key==='occupancy'&&!Number.isInteger(v)))throw Error('Invalid '+key+' value.');out[key]=v;}
 const timestamp=payload.timestamp?Date.parse(payload.timestamp):now;if(!Number.isFinite(timestamp)||timestamp>now+60000)throw Error('Invalid or future timestamp.');return {...out,timestamp,source:'external'};
}
export function createSensors(spaces){const readings=new Map(),history=new Map(spaces.map(s=>[s.id,[]])),external=new Map();let tick=0;
 function step(total,now=Date.now()){tick++;total=Math.max(0,Math.min(300,Math.floor(total)));const weights=spaces.map((s,i)=>s.capacity*(.5+.5*Math.sin(i*1.7+tick*.015)**2)),sum=weights.reduce((a,b)=>a+b,0),raw=weights.map(w=>total*w/sum),counts=raw.map(Math.floor),order=raw.map((v,i)=>({i,f:v-counts[i]})).sort((a,b)=>b.f-a.f);for(let n=0,nLeft=total-counts.reduce((a,b)=>a+b,0);n<nLeft;n++)counts[order[n].i]++;spaces.forEach((s,i)=>{const occupancy=counts[i];const phase=tick*.15+i*.9;const last=readings.get(s.id);const target={temperature:21.2+1.4*Math.sin(phase*.22)+occupancy*.034,co2:440+occupancy*21+90*(1+Math.sin(phase*.3)),lux:280+210*(1+Math.sin(phase*.16)),occupancy};const r=external.get(s.id)||{spaceId:s.id,...Object.fromEntries(Object.entries(target).map(([k,v])=>[k,k==='occupancy'?v:Math.round((last?.source==='simulated'?last[k]*.72+v*.28:v)*10)/10])),timestamp:now,source:'simulated'};readings.set(s.id,r);const h=history.get(s.id);h.push({...r,recordedAt:now});if(h.length>60)h.shift();});return readings;}
 function ingest(p,now=Date.now()){const r=validateReading(p,spaces,now),old=external.get(r.spaceId);if(old&&r.timestamp<old.timestamp)throw Error('Reading is older than the latest accepted sample.');external.set(r.spaceId,r);readings.set(r.spaceId,r);return {...r};}
 return {step,ingest,readings,history,reset:id=>external.delete(id),external};}
export function heatValue(metric,reading,capacity){return metric==='occupancy'?reading.occupancy/capacity*100:reading[metric];}
