const $=id=>document.getElementById(id);let worker=null,frameReady=false,sequence=0;
const limit=200*1024*1024;
function state(loading){document.body.classList.toggle('loading',loading);$('drop').hidden=loading;$('progress-panel').hidden=!loading;}
function fail(message){worker?.terminate();worker=null;state(false);$('error').textContent=message;$('error').hidden=false;}
function transfers(data){return Object.values(data.geometries).flatMap(g=>[g.vertices?.buffer,g.indices?.buffer].filter(Boolean));}
window.addEventListener('message',e=>{if(e.source!==$('viewer').contentWindow||e.origin!==location.origin)return;if(e.data?.type==='viewer-ready')frameReady=true;if(e.data?.type==='viewer-error'){document.body.classList.remove('viewing');$('model-area').hidden=true;fail('The viewer could not display this model: '+e.data.message);}if(e.data?.type==='viewer-loaded'){state(false);document.body.classList.add('viewing');$('model-area').hidden=false;$('viewer').hidden=false;$('replace').hidden=false;}});
async function open(file){if(!file)return;$('error').hidden=true;if(location.protocol==='file:'){fail('Serve this folder over HTTP to load the IFC engine. In its parent directory run: python3 -m http.server 8080 --directory dist, then open http://localhost:8080.');return;}if(!/\.ifc$/i.test(file.name)){fail('Choose an uncompressed .ifc file. Export .rvt files to IFC first.');return;}if(file.size>limit){fail('This prototype accepts files up to 200 MB. Export a smaller model or a discipline-specific IFC.');return;}if(!file.size){fail('This file is empty.');return;}const ticket=++sequence;worker?.terminate();state(true);$('progress-text').textContent='Reading '+file.name+'…';
 try{const buffer=await file.arrayBuffer();if(ticket!==sequence)return;const header=new TextDecoder().decode(buffer.slice(0,512));if(!header.includes('ISO-10303-21'))throw Error('This is not a supported STEP IFC file. IFCZIP and IFCXML must be exported as .ifc first.');worker=new Worker('./worker.mjs',{type:'module'});worker.onerror=e=>fail('The IFC engine could not run. Check browser memory and that all vendor files are served over HTTP. '+(e.message||''));worker.onmessage=async e=>{if(ticket!==sequence)return;if(e.data.type==='progress')$('progress-text').textContent=e.data.text;else if(e.data.type==='error')fail(e.data.message);else if(e.data.type==='model'){const data=e.data.data;worker.terminate();worker=null;$('progress-text').textContent='Opening the 3D viewer…';$('filename').textContent=file.name+' · '+data.elementCount.toLocaleString()+' elements · '+data.spaceCount+' spaces';$('report-list').replaceChildren();for(const note of data.warnings){const li=document.createElement('li');li.textContent=note;$('report-list').append(li);}$('report').hidden=!data.warnings.length;$('report-title').textContent=data.warnings.length+' import note'+(data.warnings.length===1?'':'s');
 frameReady=false;$('viewer').src='./viewer.html?model='+ticket;let elapsed=0;while(!frameReady){await new Promise(r=>setTimeout(r,50));if(ticket!==sequence)return;if((elapsed+=50)>15000){fail('The viewer did not start. Check that viewer.html is present.');return;}}if(ticket!==sequence)return;
 // Make the frame measurable before Three.js calculates camera aspect and fit.
 $('model-area').hidden=false;$('viewer').hidden=false;document.body.classList.add('viewing');$('viewer').contentWindow.postMessage({type:'load-model',data},location.origin,transfers(data));}};worker.postMessage({buffer,name:file.name},[buffer]);}catch(error){fail(error.message);}}
$('choose').onclick=()=>$('file').click();$('file').onchange=()=>{open($('file').files[0]);$('file').value='';};$('cancel').onclick=()=>{sequence++;worker?.terminate();worker=null;state(false);};$('replace').onclick=()=>{document.body.classList.remove('viewing');$('model-area').hidden=true;$('error').hidden=true;};for(const event of ['dragover','dragleave','drop'])$('drop').addEventListener(event,e=>{e.preventDefault();$('drop').classList.toggle('drag',event==='dragover');if(event==='drop')open(e.dataTransfer.files[0]);});if(location.protocol==='file:')fail('This upload tool needs a local HTTP server. See README.md for the one-command setup, or deploy dist to your static host.');
// BFH default loader is appended during the TwinXR build.
async function openDefaultBFH(){
 if(location.protocol==='file:')return;
 try{const response=await fetch('./model.json',{cache:'no-store'});if(!response.ok)throw Error('BFH model file is unavailable');const data=await response.json();
  $('filename').textContent='BFH.ifc · '+data.elements.filter(e=>e.type!=='IfcSpace').length.toLocaleString()+' elements · '+data.elements.filter(e=>e.type==='IfcSpace').length+' spaces';
  $('report').hidden=true;$('viewer').src='./viewer.html?default=bfh';frameReady=false;let elapsed=0;while(!frameReady&&elapsed<15000){await new Promise(r=>setTimeout(r,50));elapsed+=50;}
  if(!frameReady)throw Error('The BFH viewer did not start');$('model-area').hidden=false;$('viewer').hidden=false;document.body.classList.add('viewing');$('replace').hidden=false;$('viewer').contentWindow.postMessage({type:'load-model',data},location.origin,transfers(data));
 }catch(error){fail('The default BFH model could not open: '+error.message+'. Use Open another IFC to select a file.');}
}
openDefaultBFH();
