import * as T from 'three';
export function installTabletop({renderer,scene,root,sky,ground,grid,controls,getCamera,span,floors,setFloor,heatmap,prepare,restore}){
 const button=document.getElementById('enter-ar'), pivot=new T.Group(),panel=new T.Group(),buttons=[],inputs=[];scene.add(pivot,panel);panel.visible=false;
 let session=null,first=false,saved=null,drag=null,hitSource=null,placing=false;const ray=new T.Raycaster(),reticle=new T.Mesh(new T.RingGeometry(.07,.085,32).rotateX(-Math.PI/2),new T.MeshBasicMaterial({color:0x44ffcc}));scene.add(reticle);reticle.visible=false;reticle.matrixAutoUpdate=false;
 function label(text,action,x,y){const canvas=document.createElement('canvas');canvas.width=640;canvas.height=96;const c=canvas.getContext('2d');c.fillStyle='#142d42';c.fillRect(0,0,640,96);c.strokeStyle='#50d9c4';c.strokeRect(2,2,636,92);c.fillStyle='white';c.font='32px sans-serif';c.textAlign='center';c.fillText(text.slice(0,34),320,60);const tex=new T.CanvasTexture(canvas);tex.colorSpace=T.SRGBColorSpace;const m=new T.Mesh(new T.PlaneGeometry(.48,.072),new T.MeshBasicMaterial({map:tex,side:T.DoubleSide}));m.position.set(x,y,0);m.userData.action=action;panel.add(m);buttons.push(m);return m;}
 let row=0;const add=(s,a)=>{label(s,a,0,-row++*.083);};
 add('FLOORS · trigger / pinch',()=>{});floors.forEach(f=>add(f.name,()=>setFloor(f.id)));
 add('Smaller  −',()=>scale(.85));add('Larger  +',()=>scale(1.15));add('Rotate left',()=>pivot.rotation.y-=.25);add('Rotate right',()=>pivot.rotation.y+=.25);add('Raise model',()=>pivot.position.y+=.1);add('Lower model',()=>pivot.position.y-=.1);add('Move here / recenter',()=>first=true);add('Place on surface',()=>placing=!placing);add('Heatmap: cycle',()=>{heatmap.selectedIndex=(heatmap.selectedIndex+1)%heatmap.options.length;heatmap.dispatchEvent(new Event('change'));});add('Exit AR',()=>session?.end());
 panel.scale.setScalar(Math.min(1,1.25/(row*.083)));
 function scale(f){pivot.scale.setScalar(T.MathUtils.clamp(pivot.scale.x*f,.3/span,2/span));}
 function cast(controller){controller.updateWorldMatrix(true,false);ray.ray.origin.setFromMatrixPosition(controller.matrixWorld);ray.ray.direction.set(0,0,-1).transformDirection(controller.matrixWorld);panel.updateMatrixWorld(true);return ray.intersectObjects(buttons,false)[0];}
 function start(input){if(!session)return;const h=cast(input.c);if(h){h.object.userData.action();return;}if(placing&&reticle.visible){pivot.position.setFromMatrixPosition(reticle.matrix);placing=false;reticle.visible=false;return;}drag={input,origin:input.c.getWorldPosition(new T.Vector3()),position:pivot.position.clone()};}
 for(let i=0;i<2;i++){const c=renderer.xr.getController(i),input={c,source:null};scene.add(c);const line=new T.Line(new T.BufferGeometry().setFromPoints([new T.Vector3(),new T.Vector3(0,0,-3)]),new T.LineBasicMaterial({color:0x4de6c5}));c.add(line);c.addEventListener('connected',e=>input.source=e.data);c.addEventListener('disconnected',()=>{input.source=null;if(drag?.input===input)drag=null;});c.addEventListener('selectstart',()=>start(input));c.addEventListener('selectend',()=>{if(drag?.input===input)drag=null;});c.addEventListener('squeezestart',()=>{if(session)drag={input,origin:c.getWorldPosition(new T.Vector3()),position:pivot.position.clone()};});c.addEventListener('squeezeend',()=>{if(drag?.input===input)drag=null;});inputs.push(input);}
 function reset(){hitSource?.cancel();hitSource=null;drag=null;placing=false;reticle.visible=false;panel.visible=false;scene.add(root);root.position.copy(saved.rootPosition);root.quaternion.copy(saved.rootQuaternion);root.scale.copy(saved.rootScale);pivot.position.set(0,0,0);pivot.rotation.set(0,0,0);pivot.scale.setScalar(1);sky.visible=saved.sky;ground.visible=saved.ground;grid.visible=saved.grid;controls.enabled=saved.controls;getCamera().position.copy(saved.cameraPosition);getCamera().quaternion.copy(saved.cameraQuaternion);renderer.setClearColor(saved.color,saved.alpha);renderer.shadowMap.enabled=saved.shadows;session=null;restore();button.textContent='Tabletop AR';button.disabled=false;}
 button.onclick=async()=>{if(session){await session.end();return;}button.disabled=true;try{const s=await navigator.xr.requestSession('immersive-ar',{requiredFeatures:['local-floor'],optionalFeatures:['hand-tracking','hit-test']});session=s;saved={rootPosition:root.position.clone(),rootQuaternion:root.quaternion.clone(),rootScale:root.scale.clone(),sky:sky.visible,ground:ground.visible,grid:grid.visible,controls:controls.enabled,cameraPosition:getCamera().position.clone(),cameraQuaternion:getCamera().quaternion.clone(),color:renderer.getClearColor(new T.Color()),alpha:renderer.getClearAlpha(),shadows:renderer.shadowMap.enabled};prepare();pivot.add(root);pivot.scale.setScalar(.85/span);sky.visible=ground.visible=grid.visible=false;controls.enabled=false;renderer.shadowMap.enabled=false;renderer.setClearColor(0,0);getCamera().position.set(0,0,0);getCamera().quaternion.identity();renderer.xr.setReferenceSpaceType('local-floor');s.addEventListener('end',reset,{once:true});await renderer.xr.setSession(s);first=true;panel.visible=true;button.textContent='Exit AR';button.disabled=false;try{const viewer=await s.requestReferenceSpace('viewer');hitSource=await s.requestHitTestSource({space:viewer});}catch{} }catch(e){if(session){await session.end();}button.disabled=false;button.title=e.message;document.getElementById('notice').hidden=false;document.getElementById('notice').textContent='AR could not start: '+e.message;}};
 if(navigator.xr)navigator.xr.isSessionSupported('immersive-ar').then(ok=>{button.disabled=!ok;}).catch(()=>{});
 function step(frame){if(!session||!frame)return;const ref=renderer.xr.getReferenceSpace(),pose=frame.getViewerPose(ref);if(first&&pose){const p=pose.transform.position,q=pose.transform.orientation;const dir=new T.Vector3(0,0,-1).applyQuaternion(new T.Quaternion(q.x,q.y,q.z,q.w));dir.y=0;dir.normalize();pivot.position.set(p.x+dir.x*1.35,p.y-.9,p.z+dir.z*1.35);pivot.rotation.y=Math.atan2(dir.x,dir.z)+Math.PI+.65;const right=new T.Vector3(-dir.z,0,dir.x);panel.position.copy(pivot.position).addScaledVector(right,.85);panel.position.y=p.y+.1;panel.lookAt(p.x,panel.position.y,p.z);first=false;}
 if(drag&&drag.input.source?.targetRaySpace&&frame.getPose(drag.input.source.targetRaySpace,ref)){const p=drag.input.c.getWorldPosition(new T.Vector3());pivot.position.copy(drag.position).add(p.sub(drag.origin));}
 for(const input of inputs){const axes=input.source?.gamepad?.axes;if(axes?.length>=4){if(Math.abs(axes[2])>.18)pivot.rotation.y-=axes[2]*.025;if(Math.abs(axes[3])>.18)scale(Math.exp(-axes[3]*.018));}}
 reticle.visible=false;if(placing&&hitSource){const h=frame.getHitTestResults(hitSource)[0],p=h?.getPose(ref);if(p){reticle.matrix.fromArray(p.transform.matrix);reticle.visible=true;}}
 }
 return {step,get active(){return !!session;}};
}
